use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

/// Default port the Remote Control listener binds to.
pub const DEFAULT_PORT: u16 = 21772;

/// Persisted shape of `~/.config/spk-editor/remote-control.json`.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RemoteControlSettings {
    /// The public address the listener advertises (e.g. `203.0.113.1`).
    /// Filled in by the user (or the "Detect" button hitting an external
    /// echo service). `None` until configured.
    #[serde(default)]
    pub server_address: Option<String>,
    /// Port the listener binds to. Defaults to `DEFAULT_PORT`.
    #[serde(default = "default_port")]
    pub server_port: u16,
    /// User-facing on/off toggle. Flipping this to `true` triggers
    /// listener start; `false` shuts it down.
    #[serde(default)]
    pub enabled: bool,
    /// Authorized client list. Empty by default.
    #[serde(default)]
    pub clients: Vec<AuthorizedClient>,
}

impl Default for RemoteControlSettings {
    fn default() -> Self {
        Self {
            server_address: None,
            server_port: DEFAULT_PORT,
            enabled: false,
            clients: Vec::new(),
        }
    }
}

fn default_port() -> u16 {
    DEFAULT_PORT
}

/// A client allowed to connect to the Remote Control listener.
/// The `secret_base64` is a 32-byte random secret generated by the editor
/// when the client is added (so the client can be pre-provisioned via a
/// QR code in R-1.5).
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthorizedClient {
    pub name: String,
    pub secret_base64: String,
    pub created_at: DateTime<Utc>,
}

#[cfg(test)]
mod tests {
    use super::*;
    use pretty_assertions::assert_eq;

    #[test]
    fn defaults() {
        let settings = RemoteControlSettings::default();
        assert!(settings.server_address.is_none());
        assert_eq!(settings.server_port, DEFAULT_PORT);
        assert!(!settings.enabled);
        assert!(settings.clients.is_empty());
    }

    #[test]
    fn json_round_trip() {
        let original = RemoteControlSettings {
            server_address: Some("203.0.113.1".into()),
            server_port: 8080,
            enabled: true,
            clients: vec![AuthorizedClient {
                name: "Phone".into(),
                secret_base64: "AAAA".into(),
                created_at: DateTime::<Utc>::from_timestamp(1_700_000_000, 0)
                    .expect("valid timestamp"),
            }],
        };
        let text = serde_json::to_string(&original).expect("serialize");
        let parsed: RemoteControlSettings = serde_json::from_str(&text).expect("deserialize");
        assert_eq!(original, parsed);
    }

    #[test]
    fn json_partial_uses_defaults() {
        // Pre-existing file may be missing keys after upgrades; ensure
        // serde fills in defaults rather than failing.
        let text = "{}";
        let parsed: RemoteControlSettings = serde_json::from_str(text).expect("deserialize");
        assert_eq!(parsed, RemoteControlSettings::default());
    }

    #[test]
    fn json_keeps_unknown_clients_field_shape() {
        let text = r#"{ "clients": [ { "name": "A", "secret_base64": "xx", "created_at": "2024-01-01T00:00:00Z" } ] }"#;
        let parsed: RemoteControlSettings = serde_json::from_str(text).expect("deserialize");
        assert_eq!(parsed.clients.len(), 1);
        assert_eq!(parsed.clients[0].name, "A");
    }
}
