use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

/// Default port the (future) Remote Control listener binds to.
pub const DEFAULT_PORT: u16 = 21772;

/// Default cap on concurrent authorized clients holding a live socket.
/// Single connection covers the single-phone-paired-with-one-desktop
/// case; users with multiple paired clients (laptop + phone, two
/// phones, etc.) can bump it from the Remote Control modal.
pub const DEFAULT_MAX_CONNECTIONS: u32 = 1;

/// Persisted shape of `~/.config/spk-editor/remote-control.json`.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RemoteControlSettings {
    /// The public address the listener should advertise (e.g. `203.0.113.1`).
    /// Filled in by the user (or the "Detect" button hitting an external
    /// echo service). `None` until configured.
    #[serde(default)]
    pub server_address: Option<String>,
    /// Port the listener will bind to (R-2). Defaults to `DEFAULT_PORT`.
    #[serde(default = "default_port")]
    pub server_port: u16,
    /// User-facing toggle. R-1 wires this to UI only; no listener
    /// side-effect.
    #[serde(default)]
    pub enabled: bool,
    /// Authorized client list. Empty by default.
    #[serde(default)]
    pub clients: Vec<AuthorizedClient>,
    /// Cap on concurrent authenticated client sockets. New connections
    /// over the budget evict the longest-idle existing connection (LRU
    /// by last frame time) so a freshly-tapped phone always gets in.
    /// Defaults to [`DEFAULT_MAX_CONNECTIONS`].
    #[serde(default = "default_max_connections")]
    pub max_connections: u32,
}

impl Default for RemoteControlSettings {
    fn default() -> Self {
        Self {
            server_address: None,
            server_port: DEFAULT_PORT,
            enabled: false,
            clients: Vec::new(),
            max_connections: DEFAULT_MAX_CONNECTIONS,
        }
    }
}

fn default_port() -> u16 {
    DEFAULT_PORT
}

fn default_max_connections() -> u32 {
    DEFAULT_MAX_CONNECTIONS
}

/// A client allowed to connect to the (future) Remote Control listener.
/// The `secret_base64` is a 32-byte random secret generated by the editor
/// when the client is added (so the client can be pre-provisioned via a
/// QR code in R-1.5).
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthorizedClient {
    pub name: String,
    pub secret_base64: String,
    pub created_at: DateTime<Utc>,
}

#[cfg(test)]
mod tests {
    use super::*;
    use pretty_assertions::assert_eq;

    #[test]
    fn defaults() {
        let settings = RemoteControlSettings::default();
        assert!(settings.server_address.is_none());
        assert_eq!(settings.server_port, DEFAULT_PORT);
        assert!(!settings.enabled);
        assert!(settings.clients.is_empty());
    }

    #[test]
    fn json_round_trip() {
        let original = RemoteControlSettings {
            server_address: Some("203.0.113.1".into()),
            server_port: 8080,
            enabled: true,
            clients: vec![AuthorizedClient {
                name: "Phone".into(),
                secret_base64: "AAAA".into(),
                created_at: DateTime::<Utc>::from_timestamp(1_700_000_000, 0)
                    .expect("valid timestamp"),
            }],
            max_connections: 3,
        };
        let text = serde_json::to_string(&original).expect("serialize");
        let parsed: RemoteControlSettings = serde_json::from_str(&text).expect("deserialize");
        assert_eq!(original, parsed);
    }

    #[test]
    fn json_partial_uses_defaults() {
        // Pre-existing file may be missing keys after upgrades; ensure
        // serde fills in defaults rather than failing.
        let text = "{}";
        let parsed: RemoteControlSettings = serde_json::from_str(text).expect("deserialize");
        assert_eq!(parsed, RemoteControlSettings::default());
    }

    #[test]
    fn json_keeps_unknown_clients_field_shape() {
        let text = r#"{ "clients": [ { "name": "A", "secret_base64": "xx", "created_at": "2024-01-01T00:00:00Z" } ] }"#;
        let parsed: RemoteControlSettings = serde_json::from_str(text).expect("deserialize");
        assert_eq!(parsed.clients.len(), 1);
        assert_eq!(parsed.clients[0].name, "A");
    }
}
